# Generated by Django 2.2.1 on 2019-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books_written',
            field=models.ManyToManyField(related_name='authors', to='part2.Book'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_read',
            field=models.ManyToManyField(related_name='readers', to='part2.Book'),
        ),
    ]
